import { createElement } from 'react';
import {
  Utensils, ShoppingBag, Zap, Wifi, Home,
  GraduationCap, Heart, Car, Gamepad2, Shirt,
  Gift, PiggyBank, Briefcase, Coffee, Film,
  Music, Book, Plane, MoreHorizontal, Banknote,
  Train, Bus, Bike, Baby, Dog, Cat, Pill,
  Stethoscope, Scissors, Sparkles, Dumbbell,
  Users, User, UserCircle, UserRound, CircleUser,
  ShoppingCart, UtensilsCrossed, BookOpen,
  Camera, Tv, Wrench, Truck, Globe, Shield,
  Landmark, TrendingUp, Flame, Flower2, Gem,
  PartyPopper, HeartPulse, Star, MapPin, Receipt,
  Coins, Trees, TreeDeciduous, Brush, PaintBucket,
  HandCoins, Building2,
  Tag,
} from 'lucide-react-native';
import type { LucideIcon } from 'lucide-react-native';

export const ICON_COMPONENTS: Record<string, LucideIcon> = {
  Utensils,
  UtensilsCrossed,
  Coffee,
  ShoppingBag,
  ShoppingCart,
  Home,
  Building2,
  Flame,
  Zap,
  Wrench,
  PaintBucket,
  Car,
  Train,
  Bus,
  Bike,
  Truck,
  Plane,
  Globe,
  MapPin,
  Wifi,
  Tv,
  GraduationCap,
  Book,
  BookOpen,
  Heart,
  HeartPulse,
  Stethoscope,
  Pill,
  Dumbbell,
  Shirt,
  Scissors,
  Sparkles,
  Flower2,
  Gem,
  Gamepad2,
  Film,
  Music,
  Camera,
  Brush,
  Banknote,
  Coins,
  Receipt,
  Shield,
  Landmark,
  TrendingUp,
  HandCoins,
  Baby,
  Users,
  User,
  UserCircle,
  UserRound,
  CircleUser,
  Dog,
  Cat,
  Gift,
  PartyPopper,
  Trees,
  TreeDeciduous,
  PiggyBank,
  Briefcase,
  MoreHorizontal,
  Star,
  // BottleWine は lucide-react-native に存在しないため Wine で代替
  Wine: Gift,
};

export const ICON_NAMES = Object.keys(ICON_COMPONENTS);

export const getCategoryIcon = (iconName: string, size: number = 16, color?: string) => {
  const IconComponent = ICON_COMPONENTS[iconName] ?? Tag;
  return createElement(IconComponent, { size, color });
};
